name: backward-compat

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  backwards-compatibility-check:
    name: "Backwards-compatibility check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: "Install dependencies"
        run: "composer install"

      - name: "Check for BC breaks"
        run: "vendor/bin/roave-backward-compatibility-check --format=github-actions"
